# syntax=docker/dockerfile:1
FROM python:3.8.20-bookworm

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

ADD . /src

WORKDIR /src

RUN uv sync --frozen

RUN uv run ./flowers-ol/scripts/deploy.py -a

CMD ["uv", "run", "./flowers-ol/manage.py", "runserver", "0.0.0.0:8000"]

