# Generated by Django 3.0.4 on 2020-05-07 21:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('secondary_task', models.CharField(default='none', max_length=20)),
                ('episode_number', models.IntegerField(default=0)),
                ('n_distractors', models.IntegerField(default=0)),
                ('n_targets', models.IntegerField(default=0)),
                ('angle_max', models.IntegerField(default=0)),
                ('angle_min', models.IntegerField(default=0)),
                ('radius', models.IntegerField(default=0)),
                ('speed_min', models.FloatField(default=0)),
                ('speed_max', models.FloatField(default=0)),
                ('RSI', models.FloatField(default=0)),
                ('SRI_max', models.FloatField(default=0)),
                ('presentation_time', models.FloatField(default=0)),
                ('fixation_time', models.FloatField(default=0)),
                ('tracking_time', models.FloatField(default=0)),
                ('nb_target_retrieved', models.IntegerField(default=0)),
                ('nb_distract_retrieved', models.IntegerField(default=0)),
                ('id_session', models.IntegerField(default=0)),
                ('finished_session', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JOLD_participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind', models.IntegerField(null=True)),
                ('plat', models.IntegerField(null=True)),
                ('dist', models.IntegerField(null=True)),
                ('nb_sess_started', models.IntegerField(default=0)),
                ('nb_sess_finished', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='detection', max_length=20)),
                ('delta_orientation', models.FloatField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('answer_duration', models.FloatField(default=0)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_app.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inscription Date')),
                ('birth_date', models.DateField(blank=True, default=datetime.date.today, help_text='yyyy-mm-dd')),
                ('study', models.CharField(default='unk', max_length=10)),
                ('screen_params', models.FloatField(default=39.116)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant',
                'ordering': ['birth_date'],
            },
        ),
        migrations.CreateModel(
            name='JOLD_trial_LL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sess_number', models.IntegerField(default=0)),
                ('trial', models.IntegerField(null=True)),
                ('wind', models.DecimalField(decimal_places=2, max_digits=3)),
                ('init_site', models.IntegerField(null=True)),
                ('plat_site', models.IntegerField(null=True)),
                ('init_dist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('end_dist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_trial', models.DecimalField(decimal_places=1, max_digits=8)),
                ('time_sess', models.DecimalField(decimal_places=1, max_digits=8)),
                ('fuel', models.IntegerField(null=True)),
                ('presses', models.IntegerField(null=True)),
                ('outcome', models.CharField(max_length=10)),
                ('interruptions', models.IntegerField(null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_app.JOLD_participant')),
            ],
        ),
    ]
