# Generated by Django 3.0.4 on 2020-03-30 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
