# Generated by Django 3.0.5 on 2020-06-23 09:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='extra_json',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
