# Generated by Django 3.0.5 on 2020-05-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jold_participant',
            name='nb_followups_finished',
            field=models.IntegerField(default=0),
        ),
    ]
