# Generated by Django 3.0.5 on 2020-05-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_jold_participant_nb_followups_finished'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JOLD_trial_LL',
            new_name='JOLD_LL_trial',
        ),
    ]
