# Generated by Django 3.0.4 on 2020-03-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_auto_20200330_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='score',
            field=models.CharField(default='[x,x]', max_length=20),
        ),
    ]
