# Generated by Django 3.0.5 on 2020-06-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0003_auto_20200623_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
