# Generated by Django 3.0.4 on 2020-05-04 09:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface_app', '0003_auto_20200330_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='study',
            field=models.CharField(default='unk', max_length=10),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='yyyy-mm-dd'),
        ),
        migrations.CreateModel(
            name='JOLD_trial_LL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('id_session', models.IntegerField(default=0)),
                ('trial', models.IntegerField()),
                ('wind', models.DecimalField(decimal_places=2, max_digits=3)),
                ('init_site', models.IntegerField()),
                ('plat_site', models.IntegerField()),
                ('init_dist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('end_dist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_trial', models.DecimalField(decimal_places=1, max_digits=8)),
                ('time_sess', models.DecimalField(decimal_places=1, max_digits=8)),
                ('fuel', models.IntegerField()),
                ('presses', models.IntegerField()),
                ('outcome', models.CharField(max_length=10)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JOLD_params_LL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind', models.IntegerField()),
                ('plat', models.IntegerField()),
                ('dist', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
