# Generated by Django 3.0.5 on 2020-06-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0004_auto_20200623_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prompt',
            field=models.CharField(default='', max_length=50),
        ),
    ]
