# Generated by Django 3.0.5 on 2020-06-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0005_auto_20200623_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prompt',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
