# Generated by Django 3.0.5 on 2020-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0005_remove_dynamicprops_greet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicprops',
            name='instructions',
            field=models.CharField(default='', max_length=50),
        ),
    ]
