# Generated by Django 3.0.5 on 2020-06-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0006_auto_20200623_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='interface_app.ExperimentSession'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='task_stack_csv',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
