# Generated by Django 3.0.5 on 2020-05-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0006_dynamicprops_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicprops',
            name='nb_sess',
            field=models.IntegerField(default=5),
        ),
    ]
