# Generated by Django 3.0.5 on 2020-06-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0007_auto_20200624_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='message',
        ),
    ]
