# Generated by Django 3.0.5 on 2020-05-14 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0008_auto_20200513_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='dist',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='nb_followups_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='plat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='wind',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jold_ll_trial',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_app.ParticipantProfile'),
        ),
        migrations.DeleteModel(
            name='JOLD_participant',
        ),
    ]
