# Generated by Django 3.1.7 on 2021-03-24 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiment_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JOLD_LL_trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('trial', models.IntegerField(null=True)),
                ('wind', models.DecimalField(decimal_places=2, max_digits=3)),
                ('init_site', models.IntegerField(null=True)),
                ('plat_site', models.IntegerField(null=True)),
                ('init_dist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('end_dist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_trial', models.DecimalField(decimal_places=1, max_digits=8)),
                ('time_block', models.DecimalField(decimal_places=1, max_digits=8)),
                ('fuel', models.IntegerField(null=True)),
                ('presses', models.IntegerField(null=True)),
                ('outcome', models.CharField(max_length=10)),
                ('interruptions', models.IntegerField(null=True)),
                ('forced', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiment_manager_app.participantprofile')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='experiment_manager_app.experimentsession')),
            ],
            options={
                'verbose_name': 'Lunar lander trial',
                'verbose_name_plural': 'Lunar lander trials',
            },
        ),
    ]
